Cache paths and has_battery
JakeRoggenbuck/auto-clock-speed pull request #267
Opened 2022-05-22 07:24 UTC by JakeRoggenbuck

fixes #168

2022-05-23 03:05 UTC, Camerooooon requested changes
One small issue

2022-05-23 03:05 UTC, Camerooooon commented on src/main.rs
> +    };
DevicePower struct instantiation is duplicated here. I recommend using the Default trait.

2022-05-23 03:15 UTC, Camerooooon commented
For some reason when I run `cargo run monit` it does not work. Something is not working. There is no error message.

2022-05-23 03:18 UTC, JakeRoggenbuck commented
i broke so much :sob: hold on i think I know what i did

2022-05-27 03:17 UTC, JakeRoggenbuck commented
It might be worth just doing a rewrite now with the new interface

2022-05-27 03:18 UTC, JakeRoggenbuck commented
I want to keep the idea of storing those paths in an object as to not recheck each time, but the other things I did aren't as important

2022-11-08 19:52 UTC, closed without merging